/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class frm_Login extends javax.swing.JFrame {

    /**
     * Creates new form frm_Login
     */
    public frm_Login() {
        initComponents();
    }
    public boolean RevisarUsuario(String usuario){
        //Funcion para Revisar si el usuario existe dentro de la BD
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM `usuarios` WHERE `usuario` =?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, usuario);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                checkUser = true;
            }
        }   catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
        return checkUser;
        }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_Log = new javax.swing.JPanel();
        lbl_Usuario = new javax.swing.JLabel();
        lbl_Clave = new javax.swing.JLabel();
        txt_Usuario = new javax.swing.JTextField();
        lbl_Inicio = new javax.swing.JLabel();
        lbl_Logo = new javax.swing.JLabel();
        btn_Inicio = new javax.swing.JButton();
        txt_Clave = new javax.swing.JPasswordField();
        tb_Mostrar = new javax.swing.JToggleButton();
        lbl_Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Usuario.setText("Usuario:");
        lbl_Usuario.setToolTipText("");

        lbl_Clave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Clave.setText("Clave:");

        lbl_Inicio.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_Inicio.setText("Inicio de Sesion");

        btn_Inicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Inicio.setText("Inicio");
        btn_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InicioActionPerformed(evt);
            }
        });

        tb_Mostrar.setText("Mostrar");
        tb_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_MostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_LogLayout = new javax.swing.GroupLayout(jp_Log);
        jp_Log.setLayout(jp_LogLayout);
        jp_LogLayout.setHorizontalGroup(
            jp_LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_LogLayout.createSequentialGroup()
                .addGroup(jp_LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_LogLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbl_Logo))
                    .addGroup(jp_LogLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jp_LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Inicio)
                            .addGroup(jp_LogLayout.createSequentialGroup()
                                .addGroup(jp_LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Usuario)
                                    .addComponent(lbl_Clave))
                                .addGap(18, 18, 18)
                                .addGroup(jp_LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Clave)
                                    .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tb_Mostrar))))
                    .addGroup(jp_LogLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btn_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jp_LogLayout.setVerticalGroup(
            jp_LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_LogLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jp_LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Inicio)
                    .addComponent(lbl_Logo))
                .addGap(68, 68, 68)
                .addGroup(jp_LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Usuario)
                    .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jp_LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Clave)
                    .addComponent(txt_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_Mostrar))
                .addGap(44, 44, 44)
                .addComponent(btn_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jp_Log, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 470, 360));

        lbl_Imagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\santi\\OneDrive\\Escritorio\\TT.jpg")); // NOI18N
        getContentPane().add(lbl_Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btn_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InicioActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String Usuario, Clave;
        Usuario = txt_Usuario.getText();
        Clave = String.valueOf(txt_Clave.getPassword());
        String query = "SELECT * FROM `usuarios` WHERE `Usuario` =? AND `Clave` =?";
        
        try{
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, Usuario);
            ps.setString(2, Clave);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
            frm_Main mf = new frm_Main();
            mf.setVisible(true);
            mf.pack();
            this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Usuario o Clave incorrectos", "Fallo en Acesso",2);
            }
            }   catch (SQLException ex){
            Logger.getLogger(frm_Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error" + ex);
            
        }
        
    }//GEN-LAST:event_btn_InicioActionPerformed

    private void tb_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_MostrarActionPerformed
        // TODO add your handling code here:
        
        if (tb_Mostrar.isSelected()){
            txt_Clave.setEchoChar((char)0);
            tb_Mostrar.setText("Esconder");
        }
        else {
            txt_Clave.setEchoChar('\u25cf');
            tb_Mostrar.setText("Mostrar");

        }
    }//GEN-LAST:event_tb_MostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Inicio;
    private javax.swing.JPanel jp_Log;
    private javax.swing.JLabel lbl_Clave;
    private javax.swing.JLabel lbl_Imagen;
    private javax.swing.JLabel lbl_Inicio;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_Usuario;
    private javax.swing.JToggleButton tb_Mostrar;
    private javax.swing.JPasswordField txt_Clave;
    private javax.swing.JTextField txt_Usuario;
    // End of variables declaration//GEN-END:variables
}
